SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- Database: `security_db`
CREATE DATABASE IF NOT EXISTS security_db;
USE security_db;

-- Table structure for table `Caméras`
CREATE TABLE IF NOT EXISTS `Caméras` (
  `id_camera` INT PRIMARY KEY AUTO_INCREMENT,
  `emplacement` VARCHAR(255) NOT NULL,
  `statut` BOOLEAN DEFAULT 0 NOT NULL,
  `date_maj` DATE DEFAULT CURRENT_DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- Table structure for table `Alertes_Locales`
CREATE TABLE IF NOT EXISTS `Alertes_Locales` (
  `id_alerte` INT PRIMARY KEY AUTO_INCREMENT,
  `id_camera` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `date_signalement` DATE DEFAULT CURRENT_DATE,
  `statut` BOOLEAN DEFAULT 0 NOT NULL,
  CONSTRAINT `fk_alertes_locales_cameras`
    FOREIGN KEY (`id_camera`) REFERENCES `Caméras`(`id_camera`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table structure for table `Capteurs_Intrusion`
CREATE TABLE IF NOT EXISTS `Capteurs_Intrusion` (
  `id_capteur` INT PRIMARY KEY AUTO_INCREMENT,
  `emplacement` VARCHAR(255) NOT NULL,
  `niveau_alerte` BOOLEAN DEFAULT 0 NOT NULL,
  `date_signalement` DATE DEFAULT CURRENT_DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;